export const bookDetail = {
	"image": "https://img3.doubanio.com\/view\/event_poster\/median\/public\/426dd9ea3ecc574.jpg",
	"adapt_url": "https:\/\/www.douban.com\/location\/partner\/event\/28257438\/",
	"loc_name": "北京",
	"owner": {
		"name": "国家博物馆",
		"avatar": "https://img3.doubanio.com\/view\/site\/small\/public\/6510ea4ea1cc8e6.jpg",
		"uid": "127320",
		"alt": "https:\/\/site.douban.com\/127320\/",
		"type": "site",
		"id": "127320",
		"large_avatar": "https://img3.doubanio.com\/f\/shire\/12a185c5e266280902fc44b102cf9833155f41ae\/pics\/site\/icon_default_large.png"
	},
	"alt": "https:\/\/www.douban.com\/event\/28257438\/",
	"label": null,
	"id": "28257438",
	"category": "exhibition",
	"title": "大英博物馆100件文物中的世界史",
	"wisher_count": 2250,
	"has_ticket": false,
	"content": "展期：2017\/3\/2 - 5\/31\r<br>地点：北10 展厅\r<br>主办：中国国家博物馆、大英博物馆\r<br>票价：50元（票价以官网公布为准）\r<br>展览详情：<a rel=\"nofollow\" href=\"http:\/\/www.chnmuseum.cn\/Portals\/0\/web\/zt\/20170301ahow\/index.html\" target=\"_blank\">http:\/\/www.chnmuseum.cn\/Portals\/0\/web\/zt\/20170301ahow\/index.html<\/a>\r<br>\r<br>展览借助大英博物馆丰富藏品中精选出的100件（套）文物，以一种独特的方式——借助文物的视角——遨游世界历史。这个展览不仅彰显了“以物述史”的独特魅力，而且启迪我们思考自身与人类创造物之间微妙的关系。\r<br>\r<br>这些文物跨越了200万年的历史，涵盖了世界所有地区的文明。展览平等地看待人类曾经存在和当代仍然存在的各个文明，力图发现每个文明自身的价值及其对人类历史的贡献。\r<br>\r<br>那些没有留下文字记录的消亡的族群，我们可以凭借文物遗存复原他们的生活，探寻他们的精神世界。以古印度文明的石质印章为例，这枚石质印章制作于公元前2,500到前2,000年之间，来自古印度文明，一个曾繁盛于今巴基斯坦和北印度地区的印度河谷的古老文化。可能由于气候的变迁，古印度文明衰落了，在人类的记忆中消失了数千年。直到这些印章及其他遗存在19世纪的考古发掘中被发现，印度文明才重见天日。\r<br>\r<br>另一些文物则展现了人类最严肃的思考：人们渴望理解神明，超越死亡（与死神讨价还价）及战争与冲突的泥淖。例如来自也门的青铜手，属于已经消失的宗教遗产。公元后第一个千年内，几个世界性宗教兴起，导致崇拜地方神祇的小型宗教走向衰落并逐渐消失。青铜手上的铭文记录了一位神祗的名字，他在公元100—300年间受到也门山城居民的崇拜。铭文还告诉我们，这座山城叫作“里阳”，神叫作“塔拉布·里阳”，意即“里阳的强者”。他被视为里阳百姓的保护神，一位信徒将这件青铜手当作祭品奉献给他。在这件器物制作时代，数百个行形形色色的神祗在阿拉伯半岛受到崇拜。之后，琐罗亚斯德教、基督教先后到来；最终，伊斯兰教永久改变了中东地区的宗教版图。青铜手也极具个性化：折断的小拇指和罕见的勺形指甲，似乎暗示这只手是根据真人的手浇铸而成。青铜手所献祭的宗教已经消失，但这一文化遗存仍能帮助我们追寻那消失的信仰。\r<br>\r<br>还有些文物表现了人类的欢愉，专门用于华宴和游戏的场合。来自中国春秋时代的青铜镈钟，代表了早期中国“钟鸣鼎食”的礼乐文明。还有一些重要的文物揭示了人类文明自古以来存在的紧密联系与相互影响。克里特岛出土的青铜人像，其材质和技术来自世界其他地方；德雷克环球航行纪念章，体现了人类对于未知领域的好奇与探险是如何把世界各地连结在一起的。\r<br>\r<br>总之这些历史文物能带来欢欣和愉悦、好奇和挑战，能提出问题，也能解答疑惑。最重要的是，这些文物能讲故事，它们聚集一处，共同讲述了一个最伟大的故事——世界历史！\r<br>\r<br><div class=\"middle\"><img src=\"https://img3.doubanio.com\/view\/page_note\/large\/public\/p41811217-3.jpg\" alt=\"克洛维斯矛头\"><br><span class=\"pic-title\">克洛维斯矛头<\/span><\/div>\r<br>\r<br><div class=\"middle\"><img src=\"https://img3.doubanio.com\/view\/page_note\/large\/public\/p41811217-4.jpg\" alt=\"鸟形石杵\"><br><span class=\"pic-title\">鸟形石杵<\/span><\/div>\r<br>\r<br><div class=\"middle\"><img src=\"https://img3.doubanio.com\/view\/page_note\/large\/public\/p41811217-5.jpg\" alt=\"“大洪水”记录板\"><br><span class=\"pic-title\">“大洪水”记录板<\/span><\/div>\r<br>\r<br><div class=\"middle\"><img src=\"https://img3.doubanio.com\/view\/page_note\/large\/public\/p41811217-6.jpg\" alt=\"印度文明印章\"><br><span class=\"pic-title\">印度文明印章<\/span><\/div>\r<br>\r<br><div class=\"middle\"><img src=\"https://img1.doubanio.com\/view\/page_note\/large\/public\/p41811217-7.jpg\" alt=\"米诺斯礼拜者\"><br><span class=\"pic-title\">米诺斯礼拜者<\/span><\/div>\r<br>\r<br><div class=\"middle\"><img src=\"https://img1.doubanio.com\/view\/page_note\/large\/public\/p41811217-8.jpg\" alt=\"塔哈尔卡的“沙伯提”雕像\"><br><span class=\"pic-title\">塔哈尔卡的“沙伯提”雕像<\/span><\/div>\r<br>\r<br><div class=\"middle\"><img src=\"https://img1.doubanio.com\/view\/page_note\/large\/public\/p41811217-9.jpg\" alt=\"奥克苏斯的琐罗亚斯德教人像\"><br><span class=\"pic-title\">奥克苏斯的琐罗亚斯德教人像<\/span><\/div>\r<br>\r<br><div class=\"middle\"><img src=\"https://img3.doubanio.com\/view\/page_note\/large\/public\/p41811217-11.jpg\" alt=\"北美水獭烟斗\"><br><span class=\"pic-title\">北美水獭烟斗<\/span><\/div>\r<br>\r<br><div class=\"middle\"><img src=\"https://img3.doubanio.com\/view\/page_note\/large\/public\/p41811217-12.jpg\" alt=\"萨珊王狩猎盘\"><br><span class=\"pic-title\">萨珊王狩猎盘<\/span><\/div>\r<br>\r<br><div class=\"middle\"><img src=\"https://img3.doubanio.com\/view\/page_note\/large\/public\/p41811217-13.jpg\" alt=\"三彩文官俑\"><br><span class=\"pic-title\">三彩文官俑<\/span><\/div>\r<br>\r<br><div class=\"middle\"><img src=\"https://img3.doubanio.com\/view\/page_note\/large\/public\/p41811217-14.jpg\" alt=\"婆罗浮屠佛头\"><br><span class=\"pic-title\">婆罗浮屠佛头<\/span><\/div>\r<br>\r<br><div class=\"middle\"><img src=\"https://img3.doubanio.com\/view\/page_note\/large\/public\/p41811217-15.jpg\" alt=\"霍克森胡椒瓶\"><br><span class=\"pic-title\">霍克森胡椒瓶<\/span><\/div>\r<br>\r<br><div class=\"middle\"><img src=\"https://img3.doubanio.com\/view\/page_note\/large\/public\/p41811217-16.jpg\" alt=\"印加金羊驼\"><br><span class=\"pic-title\">印加金羊驼<\/span><\/div>\r<br>\r<br><div class=\"middle\"><img src=\"https://img1.doubanio.com\/view\/page_note\/large\/public\/p41811217-17.jpg\" alt=\"希伯来星盘\"><br><span class=\"pic-title\">希伯来星盘<\/span><\/div>\r<br>\r<br><div class=\"middle\"><img src=\"https://img1.doubanio.com\/view\/page_note\/large\/public\/p41811217-18.jpg\" alt=\"丢勒的《犀牛》\"><br><span class=\"pic-title\">丢勒的《犀牛》<\/span><\/div>\r<br>\r<br><div class=\"middle\"><img src=\"https://img1.doubanio.com\/view\/page_note\/large\/public\/p41811217-19.jpg\" alt=\"柿右卫门瓷象\"><br><span class=\"pic-title\">柿右卫门瓷象<\/span><\/div>\r<br>\r<br><div class=\"middle\"><img src=\"https://img3.doubanio.com\/view\/page_note\/large\/public\/p41811217-20.jpg\" alt=\"宗教改革百年纪念宣传画\"><br><span class=\"pic-title\">宗教改革百年纪念宣传画<\/span><\/div>\r<br>\r<br><div class=\"middle\"><img src=\"https://img3.doubanio.com\/view\/page_note\/large\/public\/p41811217-21.jpg\" alt=\"贝宁饰板：奥巴与欧洲人\"><br><span class=\"pic-title\">贝宁饰板：奥巴与欧洲人<\/span><\/div>\r<br>\r<br><div class=\"middle\"><img src=\"https://img3.doubanio.com\/view\/page_note\/large\/public\/p41811217-22.jpg\" alt=\"小猎犬号上的精密计时器\"><br><span class=\"pic-title\">小猎犬号上的精密计时器<\/span><\/div>",
	"can_invite": "no",
	"time_str": "2017.03.02 周四 起",
	"album": "1643245710",
	"participant_count": 1665,
	"tags": "国际",
	"image_hlarge": "https://img3.doubanio.com\/view\/event_poster\/hlarge\/public\/2ba28ed9bc258e0.jpg",
	"begin_time": "2017-03-02 09:00:00",
	"price_range": "50元(门票)",
	"geo": "39.905148 116.401711",
	"image_lmobile": "https://img3.doubanio.com\/view\/event_poster\/lmobile\/public\/426dd9ea3ecc574.jpg",
	"category_name": "展览",
	"loc_id": "108288",
	"url": "https:\/\/www.douban.com\/event\/28257438\/",
	"uri": "douban:\/\/douban.com\/event\/28257438",
	"fee_str": "50元(门票)",
	"end_time": "2017-05-31 17:00:00",
	"address": "北京 东城区 东长安街16号中国国家博物馆"
}